# fly.toml app configuration file generated for book-backend on 2024-11-03T01:12:40+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'book-backend'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'sqlite_data'
  destination = '/app/sqlite'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
